spring:
  datasource:
    #url: jdbc:h2:~/test
    #driver-class-name: org.h2.Driver
    url: jdbc:mysql://localhost:3306/thymeleaf?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Password!

  ## data.sql, schema.sql 사용 모드
  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # 보기 좋게 sql문
        format_sql: true
    # ddl-auto  속성을 사용할지 말지 결정하는 옵션
    generate-ddl: true
    # sql 보여주기
    show-sql: true
    database: mysql
   #database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  devtools:
    livereload:
      enabled: true

# 파일 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

upload:
  path: /picture
  imgUrl: /posts/images/

#thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true

server:
  port: 8081

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
